name: Build LEDE/OpenWrt for RK3568

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 安装依赖
      - name: Install dependencies
        run: |
          # 更换为阿里云镜像源
          sudo sed -i 's|http://archive.ubuntu.com|http://mirrors.aliyun.com|g' /etc/apt/sources.list
          sudo apt-get update
          
          # 安装基础依赖
          sudo apt-get install -y \
            build-essential \
            git \
            libncurses5-dev \
            zlib1g-dev \
            gawk \
            flex \
            quilt \
            wget \
            ccache \
            libssl-dev \
            xsltproc \
            unzip \
            bc \
            python3 \
            python3-pip \
            curl \
            clang \
            bison \
            g++ \
            libboost-all-dev \
            gcc \
            texinfo \
            liblzma-dev \
            make \
            scons

          # 如果 python3-distutils 缺失，尝试安装 python3-venv
          sudo apt-get install -y python3-venv
          
          # 如果需要，可以通过 pip 安装一些 Python 工具
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools

      # 设置目标配置
      - name: Set up LEDE configuration for RK3568
        run: |
          # 克隆 LEDE 仓库
          git clone https://github.com/coolsnowwolf/lede.git /lede
          cd /lede

          # 更新 Feeds
          ./scripts/feeds update -a
          ./scripts/feeds install -a

          # 配置目标平台和架构
          make menuconfig
          # 在 menuconfig 中手动选择目标平台为 Rockchip，并配置为 RK3568

          # 或者，使用默认配置文件进行构建
          # make defconfig

      # 开始构建
      - name: Build LEDE firmware
        run: |
          cd /lede
          make -j$(nproc) # 这里可以设置构建时使用的 CPU 核心数

      # 上传构建结果
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-firmware
          path: /lede/bin/targets
