name: Build LEDE/OpenWrt for RK3568

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 安装依赖
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            libncurses5-dev \
            zlib1g-dev \
            gawk \
            flex \
            quilt \
            wget \
            ccache \
            libssl-dev \
            xsltproc \
            unzip \
            bc \
            python3 \
            python3-distutils \
            python3-pip \
            curl \
            clang \
            bison \
            g++ \
            libboost-all-dev \
            gcc \
            python3-scons \
            texinfo \
            liblzma-dev \
            make \
            gcc-aarch64-linux-gnu

      # 设置目标配置
      - name: Set up LEDE configuration for RK3568
        run: |
          # 克隆 LEDE 仓库
          git clone https://github.com/coolsnowwolf/lede.git /lede
          cd /lede

          # 更新 Feeds
          ./scripts/feeds update -a
          ./scripts/feeds install -a

          # 配置目标平台为 RK3568
          make defconfig

      # 开始构建
      - name: Build LEDE firmware
        run: |
          cd /lede
          make -j$(nproc) # 使用所有 CPU 核心进行构建

      # 上传构建结果
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-firmware
          path: /lede/bin/targets
