name: LEDE Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Setup Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Build LEDE
      run: |
        git clone https://github.com/coolsnowwolf/lede.git
        cd lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make menuconfig
        make -j$(nproc)
